server:
  port: 8999
  tomcat:
    max-http-form-post-size: 1000MB

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/suhansdb
    username: root
    password: lee04290!@

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  devtools:
    livereload:
      enabled: true


mybatis:
  mapper-locations: mappers/*.xml
  config-location: classpath:mapper/config/sql-mapper-config.xml


